<?php
/* This is a template page for admin pages. It could be useful to split these up into separate templates. */

// if not defined "some var" then echo "this page cannot be accessed directly"

defined('THISISTHEKEY') or die('This page cannot be accessed directly');

// we can define what page is generated by using the key. if it has one, then a page matching the key can be generated.

// good idea, but we probably don't need to generate a completely new variable for each page, just some parts need to be done anew. -R

// Merge this page into template ???

if(constant("THISISTHEKEY") == "createpage"){

	$page = ' 
	<!doctype html>

	<head>
		<meta charset="utf-8">
		<title>Site Name - '.$title.'</title>
		<meta name="description" content="'.$description.'">
		<meta name="keywords" content="'.$keywords.'">
		<link rel="stylesheet" href="css/bootstrap.css">
	</head>

	<body>

	<div class="nav navbar navbar-inverse">

		<p class="navbar-text">Admin Page Creation</p>

	</div>

	<div class="container">

	'.$body.'

	</div>

	</body>
	</html>

	';

}

else {

	$page = ' 
	<!doctype html>

	<head>
		<meta charset="utf-8">
		<title>Site Name - '.$title.'</title>
		<meta name="description" content="'.$description.'">
		<meta name="keywords" content="'.$keywords.'">
		<link rel="stylesheet" href="css/style.css">
	</head>

	<body>	

		<h1>Header code here</h1>
		
	'.$body.'

		<div id="footer"> Footer stuff here</div>
	</body>
	</html>

	';

}

echo $page;
?>