<?php
/* This is a template page that is called by every data page, it loads the variables that the pages sends and puts all the variables into the the template page and displays is */

// if not defined "some var" then echo "this page cannot be accessed directly"

defined('THISISTHEKEY') or die('This page cannot be accessed directly');

// we can define what page is generated by using the key. if it has one, then a page matching the key can be generated.

if(constant("THISISTHEKEY") === "welcome"){

	$page = ' 
	<!doctype html>

	<head>
		<meta charset="utf-8">
		<title>Site Name - '.$title.'</title>
		<meta name="description" content="'.$description.'">
		<meta name="keywords" content="'.$keywords.'">
		<link rel="stylesheet" href="css/style.css">
	</head>

	<body>

	'.$body.'

	</body>
	</html>

	';

}

elseif(constant("THISISTHEKEY") === "blog") {

	$page = ' 
	<!doctype html>

	<head>
		<meta charset="utf-8">
		<title>Site Name - '.$title.'</title>
		<meta name="description" content="'.$description.'">
		<meta name="keywords" content="'.$keywords.'">
		<link rel="stylesheet" href="css/style.css">
	</head>

	<body>
		<div class="header">Header for blog</div>

	'.$body.'

		<div class="footer">Footer for blog</div>
	</body>
	</html>

	';

}

else {

	$page = ' 
	<!doctype html>

	<head>
		<meta charset="utf-8">
		<title>Site Name - '.$title.'</title>
		<meta name="description" content="'.$description.'">
		<meta name="keywords" content="'.$keywords.'">
		<link rel="stylesheet" href="css/style.css">
	</head>

	<body>	

		<h1>Header code here</h1>
		
	'.$body.'

		<div id="footer"> Footer stuff here</div>
	</body>
	</html>

	';

}

echo $page;
?>